require("gideon.plugins.lazy")
require("gideon.plugins.lsp")
require("gideon.plugins.mason")
require("gideon.plugins.neodev")
require("gideon.plugins.telescope")
require("gideon.plugins.treesitter")
require("gideon.plugins.cmp")
require("gideon.plugins.catpuccin")
require("gideon.plugins.devicons")
require("gideon.plugins.lualine")
require("gideon.plugins.luasnip")

